name: CI
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      ####- run: npm run format
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test step Coverage folder
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage artifact
          path: coverage
      - name: Build Projects
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build step Coverage folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build-coverage artifact
          path: build
      - name: Create a Release
        if: github.event_name == 'push'
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Staging
        if: github.event_name == 'push' && github.ref == 'refs/head/master'
        run: npx surge --project ./build --domain jumpy-stop.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
